app.host=localhost
app.port=8080

db.url=jdbc:postgresql://localhost:5432/otp_service
db.username=postgres
db.password=postgres

jwt.secret=change_this_to_a_long_random_secret_key_123456789
jwt.ttl-seconds=3600
jwt.issuer=otp-service

otp.scheduler.expiration-check-interval-seconds=30
otp.default-code-length=6
otp.default-ttl-seconds=60

file.storage.enabled=true
file.storage.path=sent-otp-codes/otp-log.txt

mail.enabled=true
mail.config-file=email.properties

smpp.enabled=true
smpp.config-file=sms.properties

telegram.enabled=true
telegram.config-file=telegram.properties

logging.requests.enabled=true
logging.sql.enabled=false