email.username=your_email@gmail.com
email.password=YOUR_APP_PASSWORD
email.from=your_email@gmail.com

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.connectiontimeout=5000
mail.smtp.timeout=5000
mail.smtp.writetimeout=5000
mail.mime.charset=UTF-8
mail.smtp.allow8bitmime=true